### ISSUE TITLE
Update reflection

### ISSUE THREAD

**Issue by katieb1** [UBC-MDS/DSCI532_Group204_R#15]
We must think critically about our app, including:
- things we did well
- potential improvements and additions
- how we addressed peer and TA feedback

* Note: point form is ok, must be < 500 words

Write ideas down in this issue for what to put in reflection.

**Comment by katieb1** [comment]
Some thoughts about working with R in dash:
- There is not as much documentation for dashR (most documentation is for python) so it was harder to find ways to make interactive elements
- It is more difficult to work with dplyr functions within a custom function because of quo/enquo
- The style of our app is completely different because you cannot use bootstrap components to make tabs, columns, rows, etc.

**Comment by jnederlo** [comment]
- We successfully implemented the most important parts of our project regarding the usefulness of the app in R, including all of the same plots and analysis.
- We couldn't implement dash bootstrap components and as a result our aesthetically pleasing design has been impacted.
- We maintained a consistent and appropriate color scheme throughout the app.
- We made efficiency improvements regarding the speed and load time of plot elements. This is an improvement over our first app.
- We successfully implemented the app in R, which is a big achievement in and of itself.

**Comment by brendoncampbell** [comment]
- ggplotly doesn't have a dedicated heatmap plot type like in altair. It's a combination of a couple of other different elements, as a result it's not as clear from the documentation how to achieve certain types of heatmap plots
- the heatmap has performance improvements over the python version when switching dropdown selections because we have pre-wrangled the data
